language: php

services:
  - mysql

php:
  - 7.1.3

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis;'
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:refresh --seed

script: ./vendor/bin/phpunit
